//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bk.APG.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bk.APG.Common.Resources.BusinessTexts", typeof(BusinessTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anhang Bundesratsantrag.
        /// </summary>
        public static string AppendixFederalCouncil_Filename {
            get {
                return ResourceManager.GetString("AppendixFederalCouncil_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehrere Dateien.
        /// </summary>
        public static string AppointmentDecision_MultipleFiles {
            get {
                return ResourceManager.GetString("AppointmentDecision_MultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wahlvorschlag.
        /// </summary>
        public static string CandidateList {
            get {
                return ResourceManager.GetString("CandidateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startdatum.
        /// </summary>
        public static string CandidateList_BeginDate {
            get {
                return ResourceManager.GetString("CandidateList_BeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jahrgang.
        /// </summary>
        public static string CandidateList_BirthYear {
            get {
                return ResourceManager.GetString("CandidateList_BirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ort.
        /// </summary>
        public static string CandidateList_City {
            get {
                return ResourceManager.GetString("CandidateList_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gremium.
        /// </summary>
        public static string CandidateList_Committee {
            get {
                return ResourceManager.GetString("CandidateList_Committee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string CandidateList_ElectionType {
            get {
                return ResourceManager.GetString("CandidateList_ElectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string CandidateList_Email {
            get {
                return ResourceManager.GetString("CandidateList_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschäftigungsgrad in Prozent.
        /// </summary>
        public static string CandidateList_EmploymentLevel {
            get {
                return ResourceManager.GetString("CandidateList_EmploymentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enddatum.
        /// </summary>
        public static string CandidateList_EndDate {
            get {
                return ResourceManager.GetString("CandidateList_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitglied der Bundesversammlung.
        /// </summary>
        public static string CandidateList_FedaralAssembly {
            get {
                return ResourceManager.GetString("CandidateList_FedaralAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Bundesdienst.
        /// </summary>
        public static string CandidateList_FedaralDuty {
            get {
                return ResourceManager.GetString("CandidateList_FedaralDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktion.
        /// </summary>
        public static string CandidateList_Function {
            get {
                return ResourceManager.GetString("CandidateList_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschlecht.
        /// </summary>
        public static string CandidateList_Gender {
            get {
                return ResourceManager.GetString("CandidateList_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string CandidateList_GivenName {
            get {
                return ResourceManager.GetString("CandidateList_GivenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interessenbindungen.
        /// </summary>
        public static string CandidateList_Interests {
            get {
                return ResourceManager.GetString("CandidateList_Interests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        public static string CandidateList_Language {
            get {
                return ResourceManager.GetString("CandidateList_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitgliederzusatz.
        /// </summary>
        public static string CandidateList_MembershipAddition {
            get {
                return ResourceManager.GetString("CandidateList_MembershipAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beruf.
        /// </summary>
        public static string CandidateList_Occupation {
            get {
                return ResourceManager.GetString("CandidateList_Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwaltungsstelle.
        /// </summary>
        public static string CandidateList_Office {
            get {
                return ResourceManager.GetString("CandidateList_Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string CandidateList_Phone {
            get {
                return ResourceManager.GetString("CandidateList_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bemerkungen.
        /// </summary>
        public static string CandidateList_Remarks {
            get {
                return ResourceManager.GetString("CandidateList_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertretung.
        /// </summary>
        public static string CandidateList_RemarkStatus {
            get {
                return ResourceManager.GetString("CandidateList_RemarkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CandidateList_Surname {
            get {
                return ResourceManager.GetString("CandidateList_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        public static string CandidateList_Title {
            get {
                return ResourceManager.GetString("CandidateList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es sind zu viele Personen aus dem Wahlvorschlag für die Validierung selektiert. Die maximale Mitgliederanzahl {0} ist überschritten. Bitte selektieren Sie weniger Personen und validieren Sie Ihre Selektion nochmal..
        /// </summary>
        public static string CandidateListValidationError_MaximumMembers {
            get {
                return ResourceManager.GetString("CandidateListValidationError_MaximumMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es sind zu wenige Personen aus dem Wahlvorschlag für die Validierung selektiert. Die minimale Mitgliederanzahl {0} ist unterschritten. Bitte selektieren Sie mehr Personen und validieren Sie Ihre Selektion nochmal..
        /// </summary>
        public static string CandidateListValidationError_MinimumMembers {
            get {
                return ResourceManager.GetString("CandidateListValidationError_MinimumMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selbstorgansisiert.
        /// </summary>
        public static string Committee_SelfOrganized {
            get {
                return ResourceManager.GetString("Committee_SelfOrganized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w.
        /// </summary>
        public static string Common_FemaleAbbreviation {
            get {
                return ResourceManager.GetString("Common_FemaleAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string Common_MaleAbbreviation {
            get {
                return ResourceManager.GetString("Common_MaleAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine.
        /// </summary>
        public static string Common_None {
            get {
                return ResourceManager.GetString("Common_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nicht vertreten.
        /// </summary>
        public static string Compare_List_Language_Missing {
            get {
                return ResourceManager.GetString("Compare_List_Language_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Untervertretung.
        /// </summary>
        public static string Compare_List_Language_OK {
            get {
                return ResourceManager.GetString("Compare_List_Language_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mann.
        /// </summary>
        public static string Compare_List_Man {
            get {
                return ResourceManager.GetString("Compare_List_Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Männer.
        /// </summary>
        public static string Compare_List_Men {
            get {
                return ResourceManager.GetString("Compare_List_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frau.
        /// </summary>
        public static string Compare_List_Woman {
            get {
                return ResourceManager.GetString("Compare_List_Woman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frauen.
        /// </summary>
        public static string Compare_List_Women {
            get {
                return ResourceManager.GetString("Compare_List_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergleichsliste GEW Überprüfung.
        /// </summary>
        public static string CompareList_FileName {
            get {
                return ResourceManager.GetString("CompareList_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ständeratin.
        /// </summary>
        public static string CouncilOfStateFemale {
            get {
                return ResourceManager.GetString("CouncilOfStateFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ständerat.
        /// </summary>
        public static string CouncilOfStateMale {
            get {
                return ResourceManager.GetString("CouncilOfStateMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total aktive Gremien.
        /// </summary>
        public static string DataAnalysis_ActiveCommitteeCount {
            get {
                return ResourceManager.GetString("DataAnalysis_ActiveCommitteeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total aktive Mitglieder.
        /// </summary>
        public static string DataAnalysis_ActiveMemberCount {
            get {
                return ResourceManager.GetString("DataAnalysis_ActiveMemberCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl aktive Mitgliedschaften.
        /// </summary>
        public static string DataAnalysis_ActiveMembershipCount {
            get {
                return ResourceManager.GetString("DataAnalysis_ActiveMembershipCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altersgruppe.
        /// </summary>
        public static string DataAnalysis_Age {
            get {
                return ResourceManager.GetString("DataAnalysis_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startdatum.
        /// </summary>
        public static string DataAnalysis_BeginDate {
            get {
                return ResourceManager.GetString("DataAnalysis_BeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jahrgang.
        /// </summary>
        public static string DataAnalysis_BirthYear {
            get {
                return ResourceManager.GetString("DataAnalysis_BirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanton.
        /// </summary>
        public static string DataAnalysis_Canton {
            get {
                return ResourceManager.GetString("DataAnalysis_Canton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Im zentralen Bundesdienst.
        /// </summary>
        public static string DataAnalysis_CentralFederalAdministrationDutyCount {
            get {
                return ResourceManager.GetString("DataAnalysis_CentralFederalAdministrationDutyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Im zentralen Bundesdienst.
        /// </summary>
        public static string DataAnalysis_CentralFederalAdministrationDutyPercentage {
            get {
                return ResourceManager.GetString("DataAnalysis_CentralFederalAdministrationDutyPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundesdienst (zentral/dezentral).
        /// </summary>
        public static string DataAnalysis_CentralFederalDuty {
            get {
                return ResourceManager.GetString("DataAnalysis_CentralFederalDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ort.
        /// </summary>
        public static string DataAnalysis_City {
            get {
                return ResourceManager.GetString("DataAnalysis_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gremium.
        /// </summary>
        public static string DataAnalysis_Committee {
            get {
                return ResourceManager.GetString("DataAnalysis_Committee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gremiumname.
        /// </summary>
        public static string DataAnalysis_CommitteeName {
            get {
                return ResourceManager.GetString("DataAnalysis_CommitteeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gremiumart.
        /// </summary>
        public static string DataAnalysis_CommitteeType {
            get {
                return ResourceManager.GetString("DataAnalysis_CommitteeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amt/Firma, Sektion.
        /// </summary>
        public static string DataAnalysis_CompanyName {
            get {
                return ResourceManager.GetString("DataAnalysis_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon (Amt/Firma).
        /// </summary>
        public static string DataAnalysis_CompanyPhone {
            get {
                return ResourceManager.GetString("DataAnalysis_CompanyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenschutzberatende.
        /// </summary>
        public static string DataAnalysis_ContactPointDataProtectionOfficer {
            get {
                return ResourceManager.GetString("DataAnalysis_ContactPointDataProtectionOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekretariate.
        /// </summary>
        public static string DataAnalysis_ContactPointSecretariat {
            get {
                return ResourceManager.GetString("DataAnalysis_ContactPointSecretariat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Im dezentralen Bundesdienst.
        /// </summary>
        public static string DataAnalysis_DecentralizedFederalAdministrationDutyCount {
            get {
                return ResourceManager.GetString("DataAnalysis_DecentralizedFederalAdministrationDutyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Im dezentralen Bundesdienst.
        /// </summary>
        public static string DataAnalysis_DecentralizedFederalAdministrationDutyPercentage {
            get {
                return ResourceManager.GetString("DataAnalysis_DecentralizedFederalAdministrationDutyPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string DataAnalysis_Department {
            get {
                return ResourceManager.GetString("DataAnalysis_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amtszeit.
        /// </summary>
        public static string DataAnalysis_Duty {
            get {
                return ResourceManager.GetString("DataAnalysis_Duty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wahlbehörde.
        /// </summary>
        public static string DataAnalysis_ElectionOffice {
            get {
                return ResourceManager.GetString("DataAnalysis_ElectionOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email-Adresse (Amt/Firma + persönlich).
        /// </summary>
        public static string DataAnalysis_EmailAddresses {
            get {
                return ResourceManager.GetString("DataAnalysis_EmailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschäftigungsgrad.
        /// </summary>
        public static string DataAnalysis_EmploymentLevel {
            get {
                return ResourceManager.GetString("DataAnalysis_EmploymentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enddatum.
        /// </summary>
        public static string DataAnalysis_EndDate {
            get {
                return ResourceManager.GetString("DataAnalysis_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausserparlamentarische Kommission.
        /// </summary>
        public static string DataAnalysis_ExtraParliamentaryCommission {
            get {
                return ResourceManager.GetString("DataAnalysis_ExtraParliamentaryCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In der Bundesversammlung.
        /// </summary>
        public static string DataAnalysis_FederalAssembly {
            get {
                return ResourceManager.GetString("DataAnalysis_FederalAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Mitglieder der Bundesversammlung.
        /// </summary>
        public static string DataAnalysis_FederalAssemblyCount {
            get {
                return ResourceManager.GetString("DataAnalysis_FederalAssemblyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Mitglieder der Bundesversammlung.
        /// </summary>
        public static string DataAnalysis_FederalAssemblyPercentage {
            get {
                return ResourceManager.GetString("DataAnalysis_FederalAssemblyPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Bundesdienst.
        /// </summary>
        public static string DataAnalysis_FederalDuty {
            get {
                return ResourceManager.GetString("DataAnalysis_FederalDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zentral.
        /// </summary>
        public static string DataAnalysis_FederalDuty_Central {
            get {
                return ResourceManager.GetString("DataAnalysis_FederalDuty_Central", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dezentral.
        /// </summary>
        public static string DataAnalysis_FederalDuty_Decentralized {
            get {
                return ResourceManager.GetString("DataAnalysis_FederalDuty_Decentralized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Im Bundesdienst.
        /// </summary>
        public static string DataAnalysis_FederalDutyCount {
            get {
                return ResourceManager.GetString("DataAnalysis_FederalDutyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Im Bundesdienst.
        /// </summary>
        public static string DataAnalysis_FederalDutyPercentage {
            get {
                return ResourceManager.GetString("DataAnalysis_FederalDutyPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Präsidentinnen.
        /// </summary>
        public static string DataAnalysis_FemalePresidentCount {
            get {
                return ResourceManager.GetString("DataAnalysis_FemalePresidentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Präsidentinnen.
        /// </summary>
        public static string DataAnalysis_FemalePresidentPercentage {
            get {
                return ResourceManager.GetString("DataAnalysis_FemalePresidentPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string DataAnalysis_FirstName {
            get {
                return ResourceManager.GetString("DataAnalysis_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Französisch.
        /// </summary>
        public static string DataAnalysis_FrenchCount {
            get {
                return ResourceManager.GetString("DataAnalysis_FrenchCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Französisch.
        /// </summary>
        public static string DataAnalysis_FrenchPercentage {
            get {
                return ResourceManager.GetString("DataAnalysis_FrenchPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seit (Startdatum Mitgliedschaft).
        /// </summary>
        public static string DataAnalysis_From {
            get {
                return ResourceManager.GetString("DataAnalysis_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktion.
        /// </summary>
        public static string DataAnalysis_Function {
            get {
                return ResourceManager.GetString("DataAnalysis_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschlecht.
        /// </summary>
        public static string DataAnalysis_Gender {
            get {
                return ResourceManager.GetString("DataAnalysis_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Deutsch.
        /// </summary>
        public static string DataAnalysis_GermanCount {
            get {
                return ResourceManager.GetString("DataAnalysis_GermanCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Deutsch.
        /// </summary>
        public static string DataAnalysis_GermanPercentage {
            get {
                return ResourceManager.GetString("DataAnalysis_GermanPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktion.
        /// </summary>
        public static string DataAnalysis_InterestFunction {
            get {
                return ResourceManager.GetString("DataAnalysis_InterestFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechtsform alt.
        /// </summary>
        public static string DataAnalysis_InterestLegalForm {
            get {
                return ResourceManager.GetString("DataAnalysis_InterestLegalForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organ.
        /// </summary>
        public static string DataAnalysis_InterestOrganization {
            get {
                return ResourceManager.GetString("DataAnalysis_InterestOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interessenbindung Text.
        /// </summary>
        public static string DataAnalysis_InterestText {
            get {
                return ResourceManager.GetString("DataAnalysis_InterestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Italienisch.
        /// </summary>
        public static string DataAnalysis_ItalianCount {
            get {
                return ResourceManager.GetString("DataAnalysis_ItalianCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Italienisch.
        /// </summary>
        public static string DataAnalysis_ItalianPercentage {
            get {
                return ResourceManager.GetString("DataAnalysis_ItalianPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        public static string DataAnalysis_Language {
            get {
                return ResourceManager.GetString("DataAnalysis_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string DataAnalysis_LastName {
            get {
                return ResourceManager.GetString("DataAnalysis_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechtsform neu.
        /// </summary>
        public static string DataAnalysis_LegalForm {
            get {
                return ResourceManager.GetString("DataAnalysis_LegalForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stufe.
        /// </summary>
        public static string DataAnalysis_Level {
            get {
                return ResourceManager.GetString("DataAnalysis_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Präsidenten.
        /// </summary>
        public static string DataAnalysis_MalePresidentCount {
            get {
                return ResourceManager.GetString("DataAnalysis_MalePresidentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Präsidenten.
        /// </summary>
        public static string DataAnalysis_MalePresidentPercentage {
            get {
                return ResourceManager.GetString("DataAnalysis_MalePresidentPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Männer.
        /// </summary>
        public static string DataAnalysis_ManCount {
            get {
                return ResourceManager.GetString("DataAnalysis_ManCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Männer.
        /// </summary>
        public static string DataAnalysis_ManPercentage {
            get {
                return ResourceManager.GetString("DataAnalysis_ManPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitgliederzusatz.
        /// </summary>
        public static string DataAnalysis_MemberAdditions {
            get {
                return ResourceManager.GetString("DataAnalysis_MemberAdditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitgliedschaft.
        /// </summary>
        public static string DataAnalysis_Membership {
            get {
                return ResourceManager.GetString("DataAnalysis_Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MitgliedschaftInteressen.
        /// </summary>
        public static string DataAnalysis_MembershipInterests {
            get {
                return ResourceManager.GetString("DataAnalysis_MembershipInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Mitglieder nicht in der Bundesversammlung.
        /// </summary>
        public static string DataAnalysis_NotFederalAssemblyCount {
            get {
                return ResourceManager.GetString("DataAnalysis_NotFederalAssemblyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Mitglieder nicht in der Bundesversammlung.
        /// </summary>
        public static string DataAnalysis_NotFederalAssemblyPercentage {
            get {
                return ResourceManager.GetString("DataAnalysis_NotFederalAssemblyPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Nicht im Bundesdienst.
        /// </summary>
        public static string DataAnalysis_NotFederalDutyCount {
            get {
                return ResourceManager.GetString("DataAnalysis_NotFederalDutyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Nicht im Bundesdienst.
        /// </summary>
        public static string DataAnalysis_NotFederalDutyPercentage {
            get {
                return ResourceManager.GetString("DataAnalysis_NotFederalDutyPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beruf.
        /// </summary>
        public static string DataAnalysis_Occupation {
            get {
                return ResourceManager.GetString("DataAnalysis_Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwaltungsstelle.
        /// </summary>
        public static string DataAnalysis_Office {
            get {
                return ResourceManager.GetString("DataAnalysis_Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string DataAnalysis_Person {
            get {
                return ResourceManager.GetString("DataAnalysis_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon (persönliche/mobil).
        /// </summary>
        public static string DataAnalysis_PersonalPhoneMobile {
            get {
                return ResourceManager.GetString("DataAnalysis_PersonalPhoneMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string DataAnalysis_Region {
            get {
                return ResourceManager.GetString("DataAnalysis_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Rätoromanisch.
        /// </summary>
        public static string DataAnalysis_RomanshCount {
            get {
                return ResourceManager.GetString("DataAnalysis_RomanshCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Rätoromanisch.
        /// </summary>
        public static string DataAnalysis_RomanshPercentage {
            get {
                return ResourceManager.GetString("DataAnalysis_RomanshPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string DataAnalysis_Status {
            get {
                return ResourceManager.GetString("DataAnalysis_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufsichts- oder Regulierungsaufgaben.
        /// </summary>
        public static string DataAnalysis_SupervisionDuty {
            get {
                return ResourceManager.GetString("DataAnalysis_SupervisionDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amtsperiode.
        /// </summary>
        public static string DataAnalysis_TermOfOffice {
            get {
                return ResourceManager.GetString("DataAnalysis_TermOfOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel, Nachname, Vorname.
        /// </summary>
        public static string DataAnalysis_TitleSurnameGivenName {
            get {
                return ResourceManager.GetString("DataAnalysis_TitleSurnameGivenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bis (Enddatum Mitgliedschaft).
        /// </summary>
        public static string DataAnalysis_To {
            get {
                return ResourceManager.GetString("DataAnalysis_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string DataAnalysis_Total {
            get {
                return ResourceManager.GetString("DataAnalysis_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Frauen.
        /// </summary>
        public static string DataAnalysis_WomanCount {
            get {
                return ResourceManager.GetString("DataAnalysis_WomanCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Frauen.
        /// </summary>
        public static string DataAnalysis_WomanPercentage {
            get {
                return ResourceManager.GetString("DataAnalysis_WomanPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APG Bundesratsbeschluss.
        /// </summary>
        public static string DecisionFederalCouncil_Filename {
            get {
                return ResourceManager.GetString("DecisionFederalCouncil_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string ElectoralList_BeginDate {
            get {
                return ResourceManager.GetString("ElectoralList_BeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jahrgang.
        /// </summary>
        public static string ElectoralList_BirthYear {
            get {
                return ResourceManager.GetString("ElectoralList_BirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanton.
        /// </summary>
        public static string ElectoralList_Canton {
            get {
                return ResourceManager.GetString("ElectoralList_Canton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wahlbehörde.
        /// </summary>
        public static string ElectoralList_ElectionOffice {
            get {
                return ResourceManager.GetString("ElectoralList_ElectionOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wahlart.
        /// </summary>
        public static string ElectoralList_ElectionType {
            get {
                return ResourceManager.GetString("ElectoralList_ElectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wahlliste.
        /// </summary>
        public static string ElectoralList_ElectoralList {
            get {
                return ResourceManager.GetString("ElectoralList_ElectoralList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ende.
        /// </summary>
        public static string ElectoralList_EndDate {
            get {
                return ResourceManager.GetString("ElectoralList_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswertungsdatum.
        /// </summary>
        public static string ElectoralList_EvaluationDate {
            get {
                return ResourceManager.GetString("ElectoralList_EvaluationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In der Bundesversammlung.
        /// </summary>
        public static string ElectoralList_FederalAssembly {
            get {
                return ResourceManager.GetString("ElectoralList_FederalAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundesrat.
        /// </summary>
        public static string ElectoralList_FederalCouncil {
            get {
                return ResourceManager.GetString("ElectoralList_FederalCouncil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Bundesdienst.
        /// </summary>
        public static string ElectoralList_FederalDuty {
            get {
                return ResourceManager.GetString("ElectoralList_FederalDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interessenbindungen.
        /// </summary>
        public static string ElectoralList_Interests {
            get {
                return ResourceManager.GetString("ElectoralList_Interests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        public static string ElectoralList_Internet {
            get {
                return ResourceManager.GetString("ElectoralList_Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        public static string ElectoralList_Language {
            get {
                return ResourceManager.GetString("ElectoralList_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitere Mitgliedschaften.
        /// </summary>
        public static string ElectoralList_OtherMemberships {
            get {
                return ResourceManager.GetString("ElectoralList_OtherMemberships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anrede, Nachname, Vorname.
        /// </summary>
        public static string ElectoralList_SalutationSurnameGivenName {
            get {
                return ResourceManager.GetString("ElectoralList_SalutationSurnameGivenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel, Beruf.
        /// </summary>
        public static string ElectoralList_TitleOccupation {
            get {
                return ResourceManager.GetString("ElectoralList_TitleOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APG Serienbrief Gesamt.
        /// </summary>
        public static string FormLetterCompleteExport_Filename {
            get {
                return ResourceManager.GetString("FormLetterCompleteExport_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte Datenschutzberater/-in nachtragen..
        /// </summary>
        public static string GeneralElection_MissingDataProtectionOfficer_TaskDescription {
            get {
                return ResourceManager.GetString("GeneralElection_MissingDataProtectionOfficer_TaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte die fehlenden Begründungen für die GEW nachtragen..
        /// </summary>
        public static string GeneralElection_MissingJustifications_TaskDescription {
            get {
                return ResourceManager.GetString("GeneralElection_MissingJustifications_TaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte das fehlende Sekretariat nachtragen..
        /// </summary>
        public static string GeneralElection_MissingSecretariat_TaskDescription {
            get {
                return ResourceManager.GetString("GeneralElection_MissingSecretariat_TaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte die Personendaten nachtragen..
        /// </summary>
        public static string GeneralElection_PersonData_TaskDescription {
            get {
                return ResourceManager.GetString("GeneralElection_PersonData_TaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die maximiale Mitgliedschafts-Dauer für dieses Mitglied wurde erreicht: .
        /// </summary>
        public static string GeneralElectionMaximumDurationExceeded {
            get {
                return ResourceManager.GetString("GeneralElectionMaximumDurationExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informationsnotiz.
        /// </summary>
        public static string Information_Note_Filename {
            get {
                return ResourceManager.GetString("Information_Note_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Mitglied(er) im Bundesdienst.
        /// </summary>
        public static string InformationNoteExport_FederalMemberCount {
            get {
                return ResourceManager.GetString("InformationNoteExport_FederalMemberCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} % Frauen.
        /// </summary>
        public static string InformationNoteExport_Female {
            get {
                return ResourceManager.GetString("InformationNoteExport_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Französisch und Italienisch nicht vertreten.
        /// </summary>
        public static string InformationNoteExport_FrenchAndItalianMissing {
            get {
                return ResourceManager.GetString("InformationNoteExport_FrenchAndItalianMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Französisch nicht vertreten.
        /// </summary>
        public static string InformationNoteExport_FrenchMissing {
            get {
                return ResourceManager.GetString("InformationNoteExport_FrenchMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italienisch nicht vertreten.
        /// </summary>
        public static string InformationNoteExport_ItalianMissing {
            get {
                return ResourceManager.GetString("InformationNoteExport_ItalianMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} % Männer.
        /// </summary>
        public static string InformationNoteExport_Male {
            get {
                return ResourceManager.GetString("InformationNoteExport_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Mitglied(er), davon {1} im Bundesdienst.
        /// </summary>
        public static string InformationNoteExport_MemberAndFederalMemberCount {
            get {
                return ResourceManager.GetString("InformationNoteExport_MemberAndFederalMemberCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Mitglied(er).
        /// </summary>
        public static string InformationNoteExport_MemberCount {
            get {
                return ResourceManager.GetString("InformationNoteExport_MemberCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Vakanz(en).
        /// </summary>
        public static string InformationNoteExport_Vacancies {
            get {
                return ResourceManager.GetString("InformationNoteExport_Vacancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bis.
        /// </summary>
        public static string Membership_Until {
            get {
                return ResourceManager.GetString("Membership_Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationalrätin.
        /// </summary>
        public static string NationalCouncilFemale {
            get {
                return ResourceManager.GetString("NationalCouncilFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationalrat.
        /// </summary>
        public static string NationalCouncilMale {
            get {
                return ResourceManager.GetString("NationalCouncilMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zentrale Bundesverwaltung.
        /// </summary>
        public static string Office_Central {
            get {
                return ResourceManager.GetString("Office_Central", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dezentrale Bundesverwaltung.
        /// </summary>
        public static string Office_Decentral {
            get {
                return ResourceManager.GetString("Office_Decentral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APG Bericht Parlament.
        /// </summary>
        public static string ParliamentaryReport_Filename {
            get {
                return ResourceManager.GetString("ParliamentaryReport_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Adresse wird nur angezeigt, wenn die Person eine aktive Mitgliedschaft hat..
        /// </summary>
        public static string Person_MaskedAddress {
            get {
                return ResourceManager.GetString("Person_MaskedAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum der Gründung: {0}.
        /// </summary>
        public static string Report_BeginDateInFuture {
            get {
                return ResourceManager.GetString("Report_BeginDateInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum der Auflösung: {0}.
        /// </summary>
        public static string Report_EndDateInPast {
            get {
                return ResourceManager.GetString("Report_EndDateInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Jahre (bis Ende {1}).
        /// </summary>
        public static string Report_LongerDutyText {
            get {
                return ResourceManager.GetString("Report_LongerDutyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswahlverfahren: {0}.
        /// </summary>
        public static string Report_SelectionProcedure {
            get {
                return ResourceManager.GetString("Report_SelectionProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gewählt von {0} bis {1}.
        /// </summary>
        public static string Report_ShorterDutyText {
            get {
                return ResourceManager.GetString("Report_ShorterDutyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl der Vakanzen: {0}.
        /// </summary>
        public static string Report_Vacancies {
            get {
                return ResourceManager.GetString("Report_Vacancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jahre.
        /// </summary>
        public static string Report_Years {
            get {
                return ResourceManager.GetString("Report_Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Term_Of_Office_Data_Separator {
            get {
                return ResourceManager.GetString("Term_Of_Office_Data_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste Vakanzen.
        /// </summary>
        public static string Vacancies_Report_Filename {
            get {
                return ResourceManager.GetString("Vacancies_Report_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GS.
        /// </summary>
        public static string Worklist_DepartmentRole {
            get {
                return ResourceManager.GetString("Worklist_DepartmentRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amt.
        /// </summary>
        public static string Worklist_OfficeRole {
            get {
                return ResourceManager.GetString("Worklist_OfficeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekretariat.
        /// </summary>
        public static string Worklist_SecretariatRole {
            get {
                return ResourceManager.GetString("Worklist_SecretariatRole", resourceCulture);
            }
        }
    }
}
