worker_processes 1;
daemon off;

error_log /dev/stderr;

events {
  worker_connections 1024;
  multi_accept on;
}

http {
  charset utf-8;

  default_type application/octet-stream;
  
  include mime.types;
  
  sendfile on;

  tcp_nopush on;
  keepalive_timeout 30;
  port_in_redirect off;

  gzip on;

  access_log /dev/stdout;

  server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;
    
    location /systemstatus {
      include includes/security_headers.conf;
      default_type application/json;
      return 200 '{"status": "Healthy"}';
    }

    # Disable caching for JSON and HTML files
    location ~* \.(?:json|html)$ {
      include includes/security_headers.conf;
      add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0";
      expires epoch;
    }

    # Enable caching for JS and CSS files
    location ~* \.(?:js|css)$ {
      include includes/security_headers.conf;
      add_header Cache-Control "public";
      expires 1y;
    }

    # Enable caching for static assets
    location ~* \.(?:svg|jpe?g|png|gif|ico|woff2?)$ {
      include includes/security_headers.conf;
      add_header Cache-Control "public, must-revalidate";
      expires 1w;
    }

    # Fallback for single-page application
    location / {
      try_files $uri /index.html;
    }
  }
}
