add_header X-Content-Type-Options nosniff always;
add_header X-Frame-Options DENY always;
add_header X-XSS-Protection "1; mode=block" always;
add_header Referrer-Policy strict-origin-when-cross-origin always;
add_header Feature-Policy "microphone 'none'; payment 'none'; camera 'none'" always;
add_header Strict-Transport-Security "max-age=16070400; includeSubDomains" always;   #set again because it may have been overridden
add_header Content-Security-Policy "default-src 'none'; script-src 'self'; img-src 'self' data:; form-action 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.admin.ch; frame-src 'self'; frame-ancestors 'self';" always;

